### ISSUE TITLE
save and recall PID settings

### ISSUE THREAD

**Issue by joshua255** [SouthEugeneRoboticsTeam/ursa-ds-mobile#3]
Being able to save and recall one set of PID constants to a file is important so the robot doesn't have to be retuned every time it is used. It would be even better if it can store different values for each robot and each configuration, and even cooler if these values could be synced between driverstations so we can switch robots and not have to retune (that could be a file manually copied between devices). Or, if you would prefer, we could try to have the robot store its PID values to its flash/eeprom memory, and transmit them to the driverstation on startup.

**Comment by andrewda** [comment]
I take it it wouldn't be easy to do this robot-side? Because this means your have to retune the PID for every device that wants to drive the robot, and that seems unfriendly/unintuitive at best.

**Comment by joshua255** [comment]
I don't think it would be too bad to do it robot side, can I try that first?

**Comment by joshua255** [comment]
I'll update this issue with a description of how the robot sends recalled values, when I think of how.

**Comment by andrewda** [comment]
@joshua255 Maybe we could have the ds send an initial "hello" message to the robot (potentially with some special data, e.g. ip address or something like that), and the robot responds with its own "hello" message, containing PID values and other recalled constants.

**Comment by joshua255** [comment]
Would you mind having a save settings on robot button?

**Comment by andrewda** [comment]
done in v2, 4 years late! :smile:
